package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Car {

  @JsonIgnore
  @ApiModelProperty(value = "Car id (generated by application)", required = true, example = "1")
  private int id;

  @ApiModelProperty(value = "Car registration number", required = true, example = "XY 12345")
  private String registrationNumber;

  @ApiModelProperty(value = "If the company is using the car also for the personal reasons", required = true, example = "true")
  private boolean personalUse;
}
