package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Car {

  @Id
  @JsonIgnore
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @ApiModelProperty(value = "Car id (generated by application)", required = true, example = "1")
  private Long id;

  @ApiModelProperty(value = "Car registration number", required = true, example = "XY 12345")
  private String registrationNumber;

  @ApiModelProperty(value = "If the company is using the car also for the personal reasons", required = true, example = "true")
  private boolean personalUse;
}
